### PR TITLE
Android Fix

### PR DESCRIPTION
**Pull request by MAJigsaw77**

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
Don't think is not tested, is tested by me :)

**Review by ghost — APPROVED** [review]

**Comment by AndreiRudenko** [comment]
Thanks, i will test it. Why we cant have the *.so files in lib folder?

**Comment by MAJigsaw77** [comment]
If are not in ndll foder, those libs are not recognized :/

**Comment by MAJigsaw77** [comment]
But if are in ndll folder, all are working fine

**Comment by MAJigsaw77** [comment]
For android

**Pull request closed without merging**
