### PR TITLE
Fix mac libs, i have tested this and it works

### PR DESCRIPTION
**Pull request by gaminbottomtext**
Hello @AndreiRudenko , i have found a .a file that worked for mac. and i am making this pull request so it can work., this one is for big sur not mavericks

### CODE REVIEW

**Comment by gaminbottomtext** [comment]
#10

**Comment by gaminbottomtext** [comment]
#3

**Comment by gaminbottomtext** [comment]
The place i got this from: https://luapower.com/ i just renamed the libluajit.a to libluajit-5-1.a.

**Comment by AndreiRudenko** [comment]
Thank you!

**Pull request merged**
